<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>$(NoWarn);CA1515</NoWarn>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.Http.Validation.Generated</InterceptorsNamespaces>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AspNetCore.FeatureManagementOptionTests" />
    <InternalsVisibleTo Include="AspNetCore.MinimalApiTests" />
    <InternalsVisibleTo Include="AspNetCore.VersioningTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AspNetCore.FeatureManagementOptions\AspNetCore.FeatureManagementOptions.csproj" />
    <ProjectReference Include="..\..\src\AspNetCore.MinimalApiExtensions\AspNetCore.MinimalApiExtensions.csproj" />
    <ProjectReference Include="..\..\src\AspNetCore.OpenApiExtensions\AspNetCore.OpenApiExtensions.csproj" />
    <ProjectReference Include="..\..\src\AspNetCore.OpenApiFeatureManagementOptions\AspNetCore.OpenApiFeatureManagementOptions.csproj" />
    <ProjectReference Include="..\..\src\AspNetCore.OpenApiOidcExtensions\AspNetCore.OpenApiOidcExtensions.csproj" />
    <ProjectReference Include="..\..\src\AspNetCore.OpenApiVersioningOptions\AspNetCore.OpenApiVersioningOptions.csproj" />
  </ItemGroup>

</Project>
