<Project>
  <ItemGroup Label="Packages">
    <PackageVersion Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
    <PackageVersion Include="GitVersion.MsBuild" Version="6.8.2" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.10" />
    <PackageVersion Include="Microsoft.FeatureManagement.AspNetCore" Version="4.6.0" />
    <PackageVersion Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.19.2" />
    <PackageVersion Include="NSubstitute" Version="6.0.0" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.16.15" />
    <PackageVersion Include="TUnit" Version="1.61.0" />
  </ItemGroup>
  <Import Project="Directory.Packages.template.props" />
</Project>
