<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute"/>
    <PackageReference Include="TUnit"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AspNetCore.OpenApiVersioningOptions\AspNetCore.OpenApiVersioningOptions.csproj"/>
  </ItemGroup>

</Project>
