<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <SkipClsCompliant>true</SkipClsCompliant>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspNetCore.FeatureManagementOptions\AspNetCore.FeatureManagementOptions.csproj"/>
    <ProjectReference Include="..\AspNetCore.OpenApiExtensions\AspNetCore.OpenApiExtensions.csproj"/>
  </ItemGroup>

</Project>
