<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute"/>
    <PackageReference Include="TUnit"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HttpClient.AuthenticationHandlers\HttpClient.AuthenticationHandlers.csproj"/>
  </ItemGroup>

</Project>
